import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin, isSupabaseConfigured } from "@/lib/supabase";
import { registerSchema, validateData } from "@/lib/validation";
import { rateLimitByIP } from "@/lib/rate-limit";
import bcrypt from "bcryptjs";

// POST /api/auth/register - Register a new user
export async function POST(request: NextRequest) {
  try {
    if (!isSupabaseConfigured || !supabaseAdmin) {
      return NextResponse.json(
        { success: false, error: "Supabase is not configured. Please set up environment variables." },
        { status: 503 }
      );
    }

    // Rate limiting
    const rateLimit = rateLimitByIP(request, { windowMs: 60 * 1000, maxRequests: 5 });
    if (!rateLimit.success) {
      return NextResponse.json(
        { success: false, error: rateLimit.error || "Too many requests" },
        { status: 429 }
      );
    }

    const body = await request.json();

    // Input validation
    const validation = validateData(registerSchema, body);
    if (!validation.success) {
      return NextResponse.json(
        { success: false, error: validation.error },
        { status: 400 }
      );
    }

    const { email, password, name, phone } = validation.data;

    // Check if user already exists
    const { data: existingUser } = await supabaseAdmin
      .from("users")
      .select("email")
      .eq("email", email)
      .single();

    if (existingUser) {
      return NextResponse.json(
        { success: false, error: "User with this email already exists" },
        { status: 409 }
      );
    }

    // Check if email exists in admin_users table
    const { data: existingAdmin } = await supabaseAdmin
      .from("admin_users")
      .select("email")
      .eq("email", email)
      .single();

    if (existingAdmin) {
      return NextResponse.json(
        { success: false, error: "This email is already registered as an admin" },
        { status: 409 }
      );
    }

    // Hash password
    const passwordHash = await bcrypt.hash(password, 10);

    // Create user in users table
    // Note: id column is auto-generated by database with DEFAULT uuid_generate_v4()
    // We explicitly don't include id - let database handle it
    const insertData = {
      email: email.trim(),
      name: name.trim(),
      phone: phone?.trim() || null,
      password_hash: passwordHash,
      role: "customer" as const,
      verified: false,
    };
    
    // Log what we're trying to insert (without password hash)
    // eslint-disable-next-line no-console
    console.log("Attempting to insert user with data:", {
      ...insertData,
      password_hash: "[REDACTED]"
    });

    const { error: insertError, data: insertDataResult } = await supabaseAdmin
      .from("users")
      .insert(insertData);
    
    // Log insert result
    // eslint-disable-next-line no-console
    console.log("Insert result:", {
      error: insertError ? {
        message: insertError.message,
        code: insertError.code,
        details: insertError.details,
        hint: insertError.hint,
      } : null,
      data: insertDataResult
    });
    
    // If insert was successful, fetch the user back
    let newUser = null;
    if (!insertError) {
      const { data: fetchedUser, error: fetchError } = await supabaseAdmin
        .from("users")
        .select("email, name, phone, role, verified, created_at")
        .eq("email", email)
        .single();
      
      if (fetchError) {
        // eslint-disable-next-line no-console
        console.error("Error fetching created user:", fetchError);
        // User was created but we can't fetch it - that's okay, they can login
        return NextResponse.json({
          success: true,
          message: "User registered successfully. Please try logging in.",
          data: {
            email: email,
            name: name,
          },
        }, { status: 201 });
      }
      
      newUser = fetchedUser;
    }

    if (insertError) {
      // eslint-disable-next-line no-console
      console.error("=== INSERT ERROR DETAILS ===");
      console.error("Error message:", insertError.message);
      console.error("Error code:", insertError.code);
      console.error("Error details:", insertError.details);
      console.error("Error hint:", insertError.hint);
      console.error("Full error object:", JSON.stringify(insertError, null, 2));
      console.error("===========================");
      
      // Check for NOT NULL constraint violation (id column missing default)
      if (insertError.code === "23502" && insertError.message?.includes("id")) {
        return NextResponse.json(
          { 
            success: false, 
            error: "Database schema error: id column is missing DEFAULT value. Please run the migration: supabase/migrations/fix_id_default.sql",
            details: insertError.message,
            hint: "The id column needs DEFAULT uuid_generate_v4() to work properly."
          },
          { status: 500 }
        );
      }
      
      // Check if this is actually an RLS (Row Level Security) issue
      if (insertError.code === "42501" || insertError.message?.includes("permission") || insertError.message?.includes("policy")) {
        return NextResponse.json(
          { 
            success: false, 
            error: "Database permission error. Please check Row Level Security (RLS) policies for the users table.",
            details: insertError.message,
            hint: "RLS policies might be blocking the insert. Check Supabase Dashboard → Authentication → Policies"
          },
          { status: 500 }
        );
      }
      
      // If column doesn't exist, we need to add it
      if (insertError.message?.includes("column") || 
          insertError.message?.includes("does not exist") || 
          insertError.code === "42703" ||
          insertError.code === "42P01") {
        let missingColumn = null;
        
        // Try multiple patterns to extract column name
        const patterns = [
          /column\s+"([^"]+)"\s+does not exist/i,
          /column\s+([a-z_]+)\s+does not exist/i,
          /column\s+"([^"]+)"/i,
          /column\s+([a-z_]+)/i,
        ];
        
        for (const pattern of patterns) {
          const match = insertError.message.match(pattern);
          if (match && match[1]) {
            missingColumn = match[1];
            break;
          }
        }
        
        // Fallback: check for common column names in error message
        if (!missingColumn) {
          if (insertError.message.toLowerCase().includes("password_hash")) {
            missingColumn = "password_hash";
          } else if (insertError.message.toLowerCase().includes("verified")) {
            missingColumn = "verified";
          } else if (insertError.message.toLowerCase().includes("role")) {
            missingColumn = "role";
          } else if (insertError.message.toLowerCase().includes("id")) {
            missingColumn = "id";
          }
        }
        
        // If we still can't find it, provide a helpful message
        if (missingColumn) {
          const migrationFile = missingColumn === "id" 
            ? "supabase/migrations/ensure_users_id_column.sql"
            : "supabase/migrations/fix_users_table_simple.sql";
          
          return NextResponse.json(
            { 
              success: false, 
              error: `Database schema needs to be updated. Please add "${missingColumn}" column to users table. Run the migration: ${migrationFile}`,
              details: insertError.message,
              errorCode: insertError.code,
              hint: insertError.hint
            },
            { status: 500 }
          );
        } else {
          // Generic error with full details
          return NextResponse.json(
            { 
              success: false, 
              error: `Database schema error. Please run the migration: supabase/migrations/fix_users_table_simple.sql to add missing columns (password_hash, verified, role) to users table.`,
              details: insertError.message,
              hint: "The users table needs password_hash, verified, and role columns."
            },
            { status: 500 }
          );
        }
      }
      
      throw insertError;
    }

    if (!newUser) {
      return NextResponse.json(
        { success: false, error: "User created but could not be retrieved. Please try logging in." },
        { status: 201 }
      );
    }

    return NextResponse.json({
      success: true,
      message: "User registered successfully",
      data: {
        email: newUser.email,
        name: newUser.name,
        role: newUser.role,
      },
    }, { status: 201 });
  } catch (error: any) {
    // eslint-disable-next-line no-console
    console.error("Registration error:", error);
    return NextResponse.json(
      { success: false, error: error.message || "Failed to register user" },
      { status: 500 }
    );
  }
}

