import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin, isSupabaseConfigured } from "@/lib/supabase";
import { registerSchema, validateData } from "@/lib/validation";
import { rateLimitByIP } from "@/lib/rate-limit";
import bcrypt from "bcryptjs";

// POST /api/auth/register - Register a new user
export async function POST(request: NextRequest) {
  try {
    if (!isSupabaseConfigured || !supabaseAdmin) {
      return NextResponse.json(
        { success: false, error: "Supabase is not configured. Please set up environment variables." },
        { status: 503 }
      );
    }

    // Rate limiting
    const rateLimit = rateLimitByIP(request, { windowMs: 60 * 1000, maxRequests: 5 });
    if (!rateLimit.success) {
      return NextResponse.json(
        { success: false, error: rateLimit.error || "Too many requests" },
        { status: 429 }
      );
    }

    const body = await request.json();

    // Input validation
    const validation = validateData(registerSchema, body);
    if (!validation.success) {
      return NextResponse.json(
        { success: false, error: validation.error },
        { status: 400 }
      );
    }

    const { email, password, name, phone } = validation.data;

    // Check if user already exists
    const { data: existingUser } = await supabaseAdmin
      .from("users")
      .select("id, email")
      .eq("email", email)
      .single();

    if (existingUser) {
      return NextResponse.json(
        { success: false, error: "User with this email already exists" },
        { status: 409 }
      );
    }

    // Check if email exists in admin_users table
    const { data: existingAdmin } = await supabaseAdmin
      .from("admin_users")
      .select("id, email")
      .eq("email", email)
      .single();

    if (existingAdmin) {
      return NextResponse.json(
        { success: false, error: "This email is already registered as an admin" },
        { status: 409 }
      );
    }

    // Hash password
    const passwordHash = await bcrypt.hash(password, 10);

    // Create user in users table
    // Note: id column is auto-generated by database, we don't need to select it explicitly
    const { data: newUser, error: insertError } = await supabaseAdmin
      .from("users")
      .insert({
        email,
        name,
        phone: phone || null,
        password_hash: passwordHash,
        role: "customer", // Default role
        verified: false,
      })
      .select("email, name, phone, role, verified, created_at")
      .single();

    if (insertError) {
      // eslint-disable-next-line no-console
      console.error("Error creating user:", insertError);
      console.error("Full error object:", JSON.stringify(insertError, null, 2));
      
      // If column doesn't exist, we need to add it
      if (insertError.message?.includes("column") || insertError.message?.includes("does not exist") || insertError.code === "42703") {
        let missingColumn = null;
        
        // Try multiple patterns to extract column name
        const patterns = [
          /column\s+"([^"]+)"\s+does not exist/i,
          /column\s+([a-z_]+)\s+does not exist/i,
          /column\s+"([^"]+)"/i,
          /column\s+([a-z_]+)/i,
        ];
        
        for (const pattern of patterns) {
          const match = insertError.message.match(pattern);
          if (match && match[1]) {
            missingColumn = match[1];
            break;
          }
        }
        
        // Fallback: check for common column names in error message
        if (!missingColumn) {
          if (insertError.message.toLowerCase().includes("password_hash")) {
            missingColumn = "password_hash";
          } else if (insertError.message.toLowerCase().includes("verified")) {
            missingColumn = "verified";
          } else if (insertError.message.toLowerCase().includes("role")) {
            missingColumn = "role";
          } else if (insertError.message.toLowerCase().includes("id")) {
            missingColumn = "id";
          }
        }
        
        // If we still can't find it, provide a helpful message
        if (missingColumn) {
          return NextResponse.json(
            { 
              success: false, 
              error: `Database schema needs to be updated. Please add "${missingColumn}" column to users table. Run the migration: supabase/migrations/fix_users_table_simple.sql`,
              details: insertError.message
            },
            { status: 500 }
          );
        } else {
          // Generic error with full details
          return NextResponse.json(
            { 
              success: false, 
              error: `Database schema error. Please run the migration: supabase/migrations/fix_users_table_simple.sql to add missing columns (password_hash, verified, role) to users table.`,
              details: insertError.message,
              hint: "The users table needs password_hash, verified, and role columns."
            },
            { status: 500 }
          );
        }
      }
      
      throw insertError;
    }

    return NextResponse.json({
      success: true,
      message: "User registered successfully",
      data: {
        email: newUser.email,
        name: newUser.name,
        role: newUser.role,
      },
    }, { status: 201 });
  } catch (error: any) {
    // eslint-disable-next-line no-console
    console.error("Registration error:", error);
    return NextResponse.json(
      { success: false, error: error.message || "Failed to register user" },
      { status: 500 }
    );
  }
}

